"""Init

Revision ID: 34939a60fc78
Revises: 
Create Date: 2025-12-03 16:26:30.265385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '34939a60fc78'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ape',
    sa.Column('ApeID', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('IPAddr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('IPV6Addr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Port', sa.Integer(), nullable=False),
    sa.Column('Longitude', sa.Float(), nullable=False),
    sa.Column('Latitude', sa.Float(), nullable=False),
    sa.Column('PlaceCode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Place', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('OrgCode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('CapDirection', sa.Enum('Front', 'Rear', name='capdirectionenum'), nullable=True),
    sa.Column('MonitorDirection', sa.Enum('WestToEast', 'EastToWest', 'NorthToSouth', 'SouthToNorth', 'SouthwestToNortheast', 'NortheastToSouthwest', 'NorthwestToSoutheast', 'SoutheastToNorthwest', 'Other', name='monitordirectionenum'), nullable=True),
    sa.Column('MonitorAreaDesc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('IsOnline', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('OwnerApsID', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('UserId', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('Password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('FunctionType', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('PositionType', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('ApeID')
    )
    op.create_table('subscribe',
    sa.Column('SubscribeID', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('SubscribeDetail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ResourceClass', sa.Enum('Tollgate', 'Ape', 'CollectedData', 'Case', 'VIID', 'AdministrativeDivision', name='resourceclassenum'), nullable=False),
    sa.Column('ResourceURI', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ApplicantName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ApplicantOrg', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('BeginTime', sa.DateTime(), nullable=False),
    sa.Column('EndTime', sa.DateTime(), nullable=False),
    sa.Column('ReceiveAddr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ReportInterval', sa.Integer(), nullable=True),
    sa.Column('Reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('OperateType', sa.Enum('Subscribe', 'Unsubscribe', name='operatetypeenum'), nullable=False),
    sa.Column('SubscribeStatus', sa.Enum('Active', 'Unsubscribed', 'Expired', 'Not_Subscribe', name='subscribestatusenum'), nullable=False),
    sa.Column('SubscribeCancelOrg', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('SubscribeCancelPerson', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('CancelTime', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('CancelReason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ResultImageDeclare', sa.Enum('Unknown', 'PersonImage', 'FaceImage', 'SceneImage', name='resultimagedeclareenum'), nullable=False),
    sa.Column('ResultFeatureDeclare', sa.Enum('WithoutFeatures', 'WithFeatures', name='resultfeaturedeclareenum'), nullable=False),
    sa.Column('TabID', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('SubscribeID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribe')
    op.drop_table('ape')
    # ### end Alembic commands ###
