"""add_non_motor_vehicle_table

Revision ID: add_non_motor_vehicle
Revises: 76a9e9cc0559
Create Date: 2026-01-04 18:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'add_non_motor_vehicle'
down_revision: Union[str, Sequence[str], None] = '76a9e9cc0559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonmotorvehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('NonMotorVehicleID', sqlmodel.sql.sqltypes.AutoString(length=33), nullable=False),
    sa.Column('InfoKind', sa.Enum('Other', 'AutoCollect', 'ManualCollect', name='infokindenum'), nullable=False),
    sa.Column('SourceID', sqlmodel.sql.sqltypes.AutoString(length=41), nullable=False),
    sa.Column('DeviceID', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('LeftTopX', sa.Integer(), nullable=True),
    sa.Column('LeftTopY', sa.Integer(), nullable=True),
    sa.Column('RightBtmX', sa.Integer(), nullable=True),
    sa.Column('RightBtmY', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('NonMotorVehicleID')
    )
    op.create_table('nonmotorvehiclesubimageinfolink',
    sa.Column('NonMotorVehicleID', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ImageID', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['ImageID'], ['subimageinfo.ImageID'], ),
    sa.ForeignKeyConstraint(['NonMotorVehicleID'], ['nonmotorvehicle.NonMotorVehicleID'], ),
    sa.PrimaryKeyConstraint('NonMotorVehicleID', 'ImageID'),
    sa.UniqueConstraint('ImageID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nonmotorvehiclesubimageinfolink')
    op.drop_table('nonmotorvehicle')
    # ### end Alembic commands ###
