REGISTER_URL = "/VIID/System/Register"
UNREGISTER_URL = "/VIID/System/UnRegister"
KEEPALIVE_URL = "/VIID/System/Keepalive"
SYSTEM_TIME_URL = "/VIID/System/Time"

APS_URL = "/VIID/APSs"
APES_URL = "/VIID/APEs"

SUBSCRIBES_URL = "/VIID/Subscribes"
SUBSCRIBE_NOTIFICATIONS_URL = "/VIID/SubscribeNotifications"

FACES_URL = "/VIID/Faces"
PERSONS_URL = "/VIID/Persons"

ARCHIVE_LIBRARIES_URL = "/VIID/ArchiveLibraries"
ARCHIVES_QUERY_SYNC_URL = "/VIID/ArchivesQuerySync"
ARCHIVES_URL = "/VIID/Archives"
ARCHIVE_SUBJECT_QUERY_SYNC_URL = "/VIID/ArchiveSubjectQuerySync"
ARCHIVE_SUBJECTS_URL = "/VIID/ArchiveSubjects"

VEHICLE_ARCHIVES_QUERY_SYNC_URL = "/VIID/VehicleArchivesQuerySync"
VEHICLE_ARCHIVES_URL = "/VIID/VehicleArchives"
VEHICLE_ARCHIVE_SUBJECT_QUERY_SYNC_URL = "/VIID/VehicleArchiveSubjectQuerySync"
VEHICLE_ARCHIVE_SUBJECTS_URL = "/VIID/VehicleArchiveSubjects"
ARCHIVE_CONFIDENCE_URL = "/VIID/ArchiveConfidence"
VEHICLE_ARCHIVE_CONFIDENCE_URL = "/VIID/VehicleArchiveConfidence"
